sudo: required

services: docker

git:
  # we don't want travis to pull them for the lint build,
  # so we pull them manually in the tests build
  submodules: false

env:
  matrix:
    - LINT_CHECK="1"
    - TESTS="1"
  global:
    - DOCKER_COMPOSE_VERSION="1.6.0"
    - TESTS="0" LINT_CHECK="0"
    - ADDONS_DIR=${TRAVIS_BUILD_DIR}/odoo/local-src
    - COMPOSE_PROJECT_NAME=depiltech

before_install:
  - sudo apt-get update
  - sudo DEBIAN_FRONTEND=noninteractive apt-get install -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" docker-engine --yes
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - git config --global user.name "TravisCI"
  - git config --global user.email "travis@camptocamp.com"
  - if [ "$LINT_CHECK" == "1" ] ; then pip install --user -q flake8 ; fi

install:
  - if [ "$LINT_CHECK" == "0" ] ; then git submodule init ; fi
  - if [ "$LINT_CHECK" == "0" ] ; then git submodule update ; fi
  - if [ "$LINT_CHECK" == "0" ] ; then docker-compose build --pull ; fi
  - if [ "$TESTS" == "1" ] ; then docker-compose up -d db ; fi
  - if [ "$TESTS" == "1" ] ; then docker-compose ps ; fi

# We run the tests and scenario in the same build, so we can push the docker image
# after that we validated it has tests and scenario passing
script:
  - if [ "$LINT_CHECK" == "1" ] ; then flake8 ${ADDONS_DIR} --exclude=__init__.py ; fi
  - if [ "$TESTS" == "1" ] ; then docker-compose run --rm -e DEMO=odoo -e RUNNING_ENV=travis odoo runtests ; fi
  # run the scenario
  - if [ "$TESTS" == "1" ] ; then docker-compose run --rm -e DEMO=scenario -e RUNNING_ENV=travis odoo odoo.py --stop-after-init ; fi

after_success:
 - if [ "$TESTS" == "1" ] ; then ./.publish.sh ; fi
