# Root file for the composition.
#
# The options specific to the development should go in
# 'docker-compose.override.yml' which is automatically applied on top of this
# file when the option '-f' of docker-compose is not used

version: '2'
services:
  odoo:
    tty: true
    build: ./odoo/
    command: odoo --load=web,web_kanban,attachment_s3,session_redis,logging_json
    depends_on:
      - db
    volumes:
      - "data-odoo:/data/odoo"
    environment:
      - SCENARIO_MAIN_TAG=depiltech
      - DB_USER=odoo
      - DB_PASSWORD=odoo
      - DB_NAME=odoodb
      - ADMIN_PASSWD=admin
      - RUNNING_ENV=dev
      - DEMO=False

  db:
    image: camptocamp/postgresql:pg9.5-latest
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - PG_SYSTEM_SHARED_BUFFERS=256MB
      - PG_SYSTEM_MAINTENANCE_WORK_MEM=256MB
      - PG_SYSTEM_WAL_BUFFERS=8MB
      - PG_SYSTEM_EFFECTIVE_CACHE_SIZE=1024MB
    volumes:
      - "data-db:/var/lib/postgresql/data"

  nginx:
    image: camptocamp/odoo-nginx:9.0
    depends_on:
      - odoo

volumes:
  data-odoo:
  data-db:
