odoo:
  image: camptocamp/depiltech_odoo:latest
  links:
    - db:db
  volumes:
    - depiltech-latest-dataodoo:/data/odoo
  environment:
    - DB_USER=${DB_USER}
    - DB_PASSWORD=${DB_PASSWORD}
    - DB_NAME=${DB_NAME}
    - DB_PORT=${DB_PORT}
    - ADMIN_PASSWD=${ADMIN_PASSWD}
    - RUNNING_ENV=${RUNNING_ENV}
    - DEMO=${DEMO}
    - WORKERS=${WORKERS}
    - MAX_CRON_THREADS=${MAX_CRON_THREADS}
    - LOG_LEVEL=${LOG_LEVEL}
    - LOG_HANDLER=${LOG_HANDLER}
    - DB_MAXCONN=${DB_MAXCONN}
    - LIMIT_MEMORY_SOFT=${LIMIT_MEMORY_SOFT}
    - LIMIT_MEMORY_HARD=${LIMIT_MEMORY_HARD}
    - LIMIT_REQUEST=${LIMIT_REQUEST}
    - LIMIT_TIME_CPU=${LIMIT_TIME_CPU}
    - LIMIT_TIME_REAL=${LIMIT_TIME_REAL}
    - MARABUNTA_ALLOW_SERIE=True
    - MARABUNTA_MODE=demo

db:
  image: camptocamp/postgresql:pg9.5-latest
  environment:
    - POSTGRES_USER=${DB_USER}
    - POSTGRES_PASSWORD=${DB_PASSWORD}
    - PG_SYSTEM_SHARED_BUFFERS=256MB
    - PG_SYSTEM_MAINTENANCE_WORK_MEM=256MB
    - PG_SYSTEM_WAL_BUFFERS=8MB
    - PG_SYSTEM_EFFECTIVE_CACHE_SIZE=1024MB
  volumes:
    - depiltech-latest-datadb:/var/lib/postgresql

nginx:
  image: camptocamp/odoo-nginx:9.0
  links:
    - odoo:odoo
